JuCheap.Core.Web/Controllers/RoleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JuCheap.Core.Interfaces;
using JuCheap.Core.Models;
using JuCheap.Core.Models.Filters;
using JuCheap.Core.Web.Filters;
using JuCheap.Core.Web.Models;
using Microsoft.AspNetCore.Mvc;
using JuCheap.Core.Infrastructure.Extentions;
using Microsoft.AspNetCore.Authorization;
using System;
using JuCheap.Core.Infrastructure.Attributes;
using JuCheap.Core.Infrastructure.Menu;

namespace JuCheap.Core.Web.Controllers
{
    /// <summary>
    /// 用户角色
    /// </summary>
    [Authorize]
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;
        private readonly IMenuService _menuService;

        public RoleController(IRoleService roleSvc,IMenuService menuService)
        {
            _roleService = roleSvc;
            _menuService = menuService;
        }

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.RolePageId, ParentId = Menu.SystemId, Name = "角色管理", Order = "5")]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.RoleAddId, ParentId = Menu.RolePageId, Name = "添加角色", Order = "1")]
        public IActionResult Add()
        {
            return View(new RoleDto());
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Menu(Id = Menu.RoleEditId, ParentId = Menu.RolePageId, Name = "编辑角色", Order = "2")]
        public async Task<IActionResult> Edit(string id)
        {
            var model = await _roleService.FindAsync(id);
            return View(model);
        }

        /// <summary>
        /// 角色授权
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.RoleAuthorizeId, ParentId = Menu.SystemId, Name = "角色授权", Order = "6")]
        public IActionResult Authen()
        {
            return View();
        }

        /// <summary>
        /// 获取菜单树
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> AuthenMenuDatas()
        {
            var list = await _menuService.GetTreesAsync();
            //默认tree节点是展开的
            list.ForEach(x => x.open = true);
            return Json(list);
        }

        /// <summary>
        /// 获取角色树
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> AuthenRoleDatas()
        {
            var list = await _roleService.GetTreesAsync();
            return Json(list);
        }

        /// <summary>
        /// 获取角色下的菜单
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> AuthenRoleMenus(string id)
        {
            var list = await _menuService.GetMenusByRoleIdAsync(id);
            var menuIds = list?.Select(item => item.Id);
            return Json(menuIds);
        }

        /// <summary>
        /// 设置角色的权限
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.RoleSetAuthorizeId, ParentId = Menu.RoleAuthorizeId, Name = "设置角色权限", Order = "1")]
        public async Task<IActionResult> SetRoleMenus([FromBody]List<RoleMenuDto> datas)
        {
            var result = new JsonResultModel<bool>();
            if (datas.AnyOne())
            {
                result.flag = await _roleService.SetRoleMenusAsync(datas);
            }
            else
            {
                result.msg = "请选择权限";
            }
            return Json(result);
        }

        /// <summary>
        /// 清空该角色下的所有权限
        /// </summary>
        /// <param name="id">角色ID</param>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.RoleCancelAuthorizeId, ParentId = Menu.RoleAuthorizeId, Name = "清空权限", Order = "2")]
        public async Task<IActionResult> ClearRoleMenus(string id)
        {
            var result = new JsonResultModel<bool>
            {
                flag = await _roleService.ClearRoleMenusAsync(id)
            };
            return Json(result);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Add(RoleDto dto)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleService.AddAsync(dto);
                if (result.IsNotBlank())
                    return RedirectToAction("Index");
            }
            return View(dto);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Edit(RoleDto dto)
        {
            if (!ModelState.IsValid) return View(dto);

            var result = await _roleService.UpdateAsync(dto);
            if (result)
                return RedirectToAction("Index");
            return View(dto);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [Menu(Id = Menu.RoleDeleteId, ParentId = Menu.RolePageId, Name = "删除角色", Order = "3")]
        public async Task<IActionResult> Delete([FromBody]IEnumerable<string> ids)
        {
            var result = new JsonResultModel<bool>();
            if (ids.AnyOne())
            {
                result.flag = await _roleService.DeleteAsync(ids);
            }
            return Json(result);
        }

        /// <summary>
        /// 搜索页面
        /// </summary>
        /// <param name="filters">查询参数</param>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> GetListWithPager(RoleFilters filters)
        {
            var result = await _roleService.SearchAsync(filters);
            return Json(result);
        }
    }
}

JuCheap.Core.Web/Views/Role/Add.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@model JuCheap.Core.Models.RoleDto

@{
    ViewBag.Title = "添加菜单";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>添加菜单</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            @using (Html.BeginForm("Add", "Role", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="form-group">
                    <label class="col-sm-3 control-label">@Html.LabelFor(m => m.Name)：</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "角色名称" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">@Html.LabelFor(m => m.Description)：</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", placeholder = "角色描述", rows = "3" })
                        @Html.ValidationMessageFor(m => m.Description)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                        <button class="btn btn-info" type="submit">保存</button>
                        <button class="btn btn-white" type="button" id="btnBack">返回</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    <environment names="Development">
        <script src="~/js/jquery.validate.js"></script>
        <script src="~/js/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/base.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/validate.min.js" asp-append-version="true"></script>
        <script src="~/js/base.min.js" asp-append-version="true"></script>
    </environment>

    <script>
        $("#btnBack").bind("click", function(e) {
            XPage.GoTo(e.target, "@Url.Action("Index")");
        });
    </script>
}

JuCheap.Core.Web/Views/Role/Authen.cshtml
@{
    ViewBag.Title = "角色授权";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}

@section styles{
   
    <environment names="Development">
        <link href="~/css/plugins/ztree/metroStyle.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/ztree.min.css" asp-append-version="true" />
    </environment>
}

@section scripts{
    <environment names="Development">
        <script src="~/js/plugins/ztree/jquery.ztree.all.js"></script>
        <script src="~/js/json2.js"></script>
        <script src="~/js/page/roleAuthen.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/ztree.min.js" asp-append-version="true"></script>
    </environment>
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>角色授权</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="row">
                <div class="col-sm-12">
                    <button id="btnSave" class="btn btn-w-m btn-primary" type="button">保存</button>
                    <button id="btnClear" class="btn btn-w-m btn-danger" type="button">清空</button>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            角色列表
                        </div>
                        <div class="panel-body">
                            <ul id="roleTree" class="ztree"></ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            权限菜单
                        </div>
                        <div class="panel-body">
                            <ul id="menuTree" class="ztree"></ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

JuCheap.Core.Web/Views/Role/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@model JuCheap.Core.Models.RoleDto

@{
    ViewBag.Title = "添加菜单";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>添加菜单</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            @using (Html.BeginForm("Edit", "Role", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="form-group">
                    <label class="col-sm-3 control-label">@Html.LabelFor(m => m.Name)：</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "角色名称" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">@Html.LabelFor(m => m.Description)：</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", placeholder = "角色描述", rows = "3" })
                        @Html.ValidationMessageFor(m => m.Description)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                        <button class="btn btn-info" type="submit">保存</button>
                        <button class="btn btn-white" type="button" id="btnBack">返回</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    <environment names="Development">
        <script src="~/js/jquery.validate.js"></script>
        <script src="~/js/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/base.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/validate.min.js" asp-append-version="true"></script>
        <script src="~/js/base.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        $("#btnBack").bind("click", function(e) {
            XPage.GoTo(e.target, "@Url.Action("Index")");
        });
    </script>
}

JuCheap.Core.Web/Views/Role/Index.cshtml
@{
    ViewBag.Title = "角色管理";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}
@section styles
{
    <environment names="Development">
        <link href="~/css/plugins/jqgrid/ui.jqgrid.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/grid.min.css" asp-append-version="true" />
    </environment>
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>@ViewBag.Title</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="form-group">
                <button id="btnAdd" type="button" class="btn btn-primary " onclick="addModel()"><i class="fa fa-check"></i>&nbsp;添加</button>
                <button id="btnEdit" type="button" class="btn btn-info " onclick="editModel()"><i class="fa fa-paste"></i> 编辑</button>
                <button id="btnDel" type="button" class="btn btn-danger " onclick="delData()">
                    <i class="fa fa-dedent"></i>&nbsp;&nbsp;<span class="bold">删除</span>
                </button>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <input id="txtSearchKey" type="text" class="input form-control" placeholder="搜索关键字" />
                    <span class="input-group-btn">
                        <button id="btnSearch" class="btn btn btn-primary" type="button"> <i class="fa fa-search"></i> 搜索</button>
                    </span>
                </div>
            </div>

            <div class="jqGrid_wrapper">
                <table id="table_list"></table>
                <div id="pager_list"></div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <environment names="Development">
        <script src="~/js/plugins/jqgrid/jquery.jqGrid.js"></script>
        <script src="~/js/plugins/jqgrid/i18n/grid.locale-cn.js"></script>
        <script src="~/js/jqgrid-list.js"></script>
        <script src="~/js/json2.js"></script>
        <script src="~/js/base.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/grid.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        function addModel() {
            $("#btnAdd").button("loading");
            window.location.href = "@Url.Action("Add")";
        }
        
        function editModel() {//编辑
            var row = JucheapGrid.GetData();
            if (row != null) {
                $("#btnEdit").button("loading");
                window.location.href = "@Url.Action("Edit")/" + row.id;
            } else {
                alert("请选择要编辑的数据");
            }
        }

        function delData() {//删除
            XPage.DelData("@Url.Action("Delete")");
        }

        function searchData() {//搜索
            var json = {
                keywords: $("#txtSearchKey").val()
            };
            XPage.Search(json);
        }
        $(document).ready(function() {
            var config = {
                title: '角色列表',
                url: '@Url.Action("GetListWithPager")',
                colNames: ['主键', '角色名称', '角色描述'],
                colModel: [
                    { name: 'id', index: 'id', width: 60, key: true, hidden: true },
                    { name: 'name', index: 'name', width: 60 },
                    { name: 'description', index: 'description', width: 100 }
                ]
            };
            JucheapGrid.Load(config);
            $("#btnSearch").bind("click", searchData);
        });
    </script>
}