JuCheap.Core.Web/Controllers/DepartmentController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JuCheap.Core.Infrastructure.Attributes;
using JuCheap.Core.Infrastructure.Extentions;
using JuCheap.Core.Infrastructure.Menu;
using JuCheap.Core.Interfaces;
using JuCheap.Core.Models;
using JuCheap.Core.Models.Filters;
using JuCheap.Core.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace JuCheap.Core.Web.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;
        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        [Menu(Id = Menu.DepartmentPageId, ParentId = Menu.SystemId, Name = "部门管理", Order = "3")]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="id">父页面ID</param>
        /// <returns></returns>
        [Menu(Id = Menu.DepartmentAddId, ParentId = Menu.DepartmentPageId, Name = "添加部门", Order = "1")]
        public async Task<ActionResult> Add(string id)
        {
            var parentDepartment = await _departmentService.Find(id);
            var model = new DepartmentDto
            {
                ParentId = id
            };
            if (parentDepartment != null)
            {
                model.ParentName = parentDepartment.FullName;
            }
            return View(model);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Add(DepartmentDto model)
        {
            if (ModelState.IsValid)
            {
                var departmentId = await _departmentService.Add(model);
                if (departmentId.IsNotBlank())
                {
                    return PartialView("CloseLayerPartial");
                }
            }
            return View(model);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns
        [Menu(Id = Menu.DepartmentEditId, ParentId = Menu.DepartmentPageId, Name = "编辑部门", Order = "2")]
        public async Task<ActionResult> Edit(string id)
        {
            var model = await _departmentService.Find(id);
            return View(model);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Edit(DepartmentDto model)
        {
            if (ModelState.IsValid)
            {
                var success = await _departmentService.Update(model);
                if (success)
                {
                    return PartialView("CloseLayerPartial");
                }
            }
            return View(model);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id">主键ID</param>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.DepartmentDeleteId, ParentId = Menu.DepartmentPageId, Name = "删除部门", Order = "3")]
        public async Task<ActionResult> Delete(string id)
        {
            var success = await _departmentService.Delete(new List<string> { id });
            return Json(new { flag = success });
        }

        /// <summary>
        /// 获取树
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost, IgnoreRightFilter]
        public async Task<ActionResult> GetTrees(TreeFilter model)
        {
            var pages = await _departmentService.FindByParentId(model.id);
            return Json(pages);
        }

        /// <summary>
        /// 获取树
        /// </summary>
        /// <param name="q">查询关键字</param>
        /// <returns></returns>
        [HttpGet, IgnoreRightFilter]
        public async Task<ActionResult> GetDepartments(string q)
        {
            var filter = new BaseFilter
            {
                page = 1,
                rows = 1000,
                keywords = q
            };
            var result = await _departmentService.Search(filter);
            var depts = new
            {
                results = result.rows.Select(x => new {id = x.Id, text = x.FullName})
            };
            return Json(depts);
        }
    }
}

JuCheap.Core.Web/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using JuCheap.Core.Interfaces;
using JuCheap.Core.Models;
using JuCheap.Core.Models.Filters;
using JuCheap.Core.Web.Filters;
using JuCheap.Core.Web.Models;
using Microsoft.AspNetCore.Mvc;
using JuCheap.Core.Infrastructure.Extentions;
using Microsoft.AspNetCore.Authorization;
using System;
using JuCheap.Core.Infrastructure.Attributes;
using JuCheap.Core.Infrastructure.Menu;

namespace JuCheap.Core.Web.Controllers
{
    /// <summary>
    /// 用户
    /// </summary>
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;
        private readonly IMapper _mapper;

        public UserController(IUserService userSvc, IRoleService roleSvc, IMapper mapper)
        {
            _userService = userSvc;
            _roleService = roleSvc;
            _mapper = mapper;
        }

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.UserPageId, ParentId = Menu.SystemId, Name = "用户管理", Order = "7")]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 用户角色授权
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.UserRoleSetPageId, ParentId = Menu.UserPageId, Name = "用户角色授权", Order = "4")]
        public IActionResult Authen(string id)
        {
            var user = new UserDto
            {
                Id = id
            };
            return View(user);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.UserAddId, ParentId = Menu.UserPageId, Name = "添加用户", Order = "1")]
        public IActionResult Add()
        {
            return View(new UserAddDto());
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Menu(Id = Menu.UserEditId, ParentId = Menu.UserPageId, Name = "编辑用户", Order = "2")]
        public async Task<IActionResult> Edit(string id)
        {
            var dto = await _userService.FindAsync(id);
            var model = _mapper.Map<UserDto, UserUpdateDto>(dto);
            return View(model);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(UserAddDto dto)
        {
            if (ModelState.IsValid)
            {
                var result = await _userService.AddAsync(dto);
                if (result.IsNotBlank())
                    return RedirectToAction("Index");
            }
            return View(dto);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserUpdateDto dto)
        {
            if (ModelState.IsValid)
            {
                var result = await _userService.UpdateAsync(dto);
                if (result)
                    return RedirectToAction("Index");
            }
            return View(dto);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [Menu(Id = Menu.UserDeleteId, ParentId = Menu.UserPageId, Name = "删除用户", Order = "3")]
        public async Task<IActionResult> Delete([FromBody]List<string> ids)
        {
            var result = new JsonResultModel<bool>();
            if (ids.AnyOne())
            {
                result.flag = await _userService.DeleteAsync(ids);
            }
            return Json(result);
        }

        /// <summary>
        /// 搜索页面
        /// </summary>
        /// <param name="filters">查询参数</param>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> GetListWithPager(UserFilters filters)
        {
            var result = await _userService.SearchAsync(filters);
            return Json(result);
        }

        /// <summary>
        /// 我的角色
        /// </summary>
        /// <param name="filters">查询参数</param>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> GetMyRoles(RoleFilters filters)
        {
            var result = await _roleService.SearchAsync(filters);
            return Json(result);
        }

        /// <summary>
        /// 我尚未拥有的角色
        /// </summary>
        /// <param name="filters">查询参数</param>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> GetNotMyRoles(RoleFilters filters)
        {
            filters.ExcludeMyRoles = true;
            var result = await _roleService.SearchAsync(filters);
            return Json(result);
        }

        /// <summary>
        /// 用户角色授权
        /// </summary>
        /// <param name="id">角色ID</param>
        /// <param name="userId">用户Id</param>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.UserRoleSetId, ParentId = Menu.UserRoleSetPageId, Name = "用户角色授权", Order = "1")]
        public async Task<IActionResult> GiveRight(string id, string userId)
        {
            var result = new JsonResultModel<bool>
            {
                flag = await _userService.GiveAsync(userId, id)
            };
            return Json(result);
        }

        /// <summary>
        /// 用户角色取消
        /// </summary>
        /// <param name="id">角色ID</param>
        /// <param name="userId">用户Id</param>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.UserRoleCancelId, ParentId = Menu.UserRoleSetPageId, Name = "用户角色取消", Order = "2")]
        public async Task<IActionResult> CancelRight(string id, string userId)
        {
            var result = new JsonResultModel<bool>
            {
                flag = await _userService.CancelAsync(userId, id)
            };
            return Json(result);
        }

        /// <summary>
        /// 验证登录名是否重复
        /// </summary>
        /// <param name="loginName">登录名</param>
        /// <returns></returns>
        [HttpGet]
        [IgnoreRightFilter]
        public async Task<IActionResult> VerifyLoginName(string loginName)
        {
            var isExists = await _userService.ExistsLoginNameAsync(null, loginName);
            return isExists ? Json("登录帐号已存在") : Json(data: true);
        }

        /// <summary>
        /// 获取树
        /// </summary>
        /// <param name="q">查询关键字</param>
        /// <returns></returns>
        [HttpGet, IgnoreRightFilter]
        public async Task<ActionResult> GetUsers(string q)
        {
            var filter = new UserFilters
            {
                page = 1,
                rows = 1000,
                keywords = q
            };
            var result = await _userService.SearchAsync(filter);
            var users = new
            {
                results = result.rows.Select(x => new { id = x.Id, text = x.LoginName })
            };
            return Json(users);
        }
    }
}

JuCheap.Core.Web/Views/User/Add.cshtml
@model JuCheap.Core.Models.UserAddDto

@{
    ViewBag.Title = "添加用户";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>添加用户</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <form asp-controller="User" asp-action="Add" class="form-horizontal" method="POST">
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="LoginName"></label>
                    <div class="col-sm-8">
                        <input asp-for="LoginName" class="form-control" placeholder="登录账号名"/>
                        <span asp-validation-for="LoginName"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="RealName"></label>
                    <div class="col-sm-8">
                        <input asp-for="RealName" class="form-control" placeholder="真实姓名" />
                        <span asp-validation-for="RealName"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="Email"></label>
                    <div class="col-sm-8">
                        <input asp-for="Email" class="form-control" placeholder="邮箱" />
                        <span asp-validation-for="Email"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="Password"></label>
                    <div class="col-sm-8">
                        <input asp-for="Password" class="form-control" placeholder="登录密码" type="password" />
                        <span asp-validation-for="Password"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="ConfirmPwd"></label>
                    <div class="col-sm-8">
                        <input asp-for="ConfirmPwd" class="form-control" placeholder="请再次输入登录密码" type="password" />
                        <span asp-validation-for="ConfirmPwd"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="DepartmentId"></label>
                    <div class="col-sm-8">
                        <select id="DepartmentId" name="DepartmentId" class="form-control"></select>
                        <span asp-validation-for="DepartmentId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                        <button class="btn btn-info" type="submit">保存</button>
                        <button class="btn btn-white" type="button" id="btnBack">返回</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section styles{    
    <link href="~/js/plugins/select2/css/select2.css" rel="stylesheet" />
}

@section scripts{
    <environment names="Development">
        <script src="~/js/jquery.validate.js"></script>
        <script src="~/js/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/base.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/validate.min.js" asp-append-version="true"></script>
        <script src="~/js/base.min.js" asp-append-version="true"></script>
    </environment>    
    <script src="~/js/plugins/select2/js/select2.js"></script>
    <script>
        $("#btnBack").bind("click", function (e) {
            XPage.GoTo(e.target, "@Url.Action("Index")");
        });
        $(function() {
            $('#DepartmentId').select2({
                placeholder: "所属部门",
                ajax: {
                    url: '@Url.Action("GetDepartments", "Department")',
                    dataType: 'json'
                }
            });
        });
    </script>
}

JuCheap.Core.Web/Views/User/Authen.cshtml
@model JuCheap.Core.Models.UserDto
@{
    ViewBag.Title = "用户角色授权";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}
@section styles
{
    <environment names="Development">
        <link href="~/css/plugins/jqgrid/ui.jqgrid.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/grid.min.css" asp-append-version="true" />
    </environment>
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>用户角色授权</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="jqGrid_wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="table_list_my"></table>
                        <div id="pager_list_my"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <table id="table_list_notmy"></table>
                        <div id="pager_list_notmy"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <environment names="Development">
        <script src="~/js/plugins/jqgrid/jquery.jqGrid.js"></script>
        <script src="~/js/plugins/jqgrid/i18n/grid.locale-cn.js"></script>
        <script src="~/js/jqgrid-list.js"></script>
        <script src="~/js/base.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/grid.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        function cancelRight(roleId) {
            XPage.DoPost(null,"@Url.Action("CancelRight")?id=" + roleId + "&userId=@Model.Id", null, function(res) {
                if (res && res.flag) {
                    reloadGrid("table_list_my");
                    reloadGrid("table_list_notmy");
                } else {
                    alert("取消失败：" + res.msg);
                }
            }, null);
        }

        function giveRight(roleId) {
            XPage.DoPost(null, "@Url.Action("GiveRight")?id=" + roleId + "&userId=@Model.Id", null, function (res) {
                if (res && res.flag) {
                    reloadGrid("table_list_my");
                    reloadGrid("table_list_notmy");
                } else {
                    alert("授权失败：" + res.msg);
                }
            }, null);
        }
        function reloadGrid(gridId) {
            $("#" + gridId).setGridParam({ search: true }).trigger("reloadGrid", [{ page: 1 }]);
        }
        $(document).ready(function() {
            var myConfig = {
                id: "table_list_my",
                pagerId: "pager_list_my",
                title: '我的角色',
                url: '@Url.Action("GetMyRoles")?UserId=@Model.Id',
                colNames: ['主键', '角色名称', '操作'],
                colModel: [
                    { name: 'id', index: 'id', width: 30, key: true, hidden: true },
                    { name: 'name', index: 'name', width: 120 },
                    { name: 'Cancel', index: 'Cancel', width: 30 }
                ],
                gridComplete: function() {
                    var ids = jQuery("#table_list_my").jqGrid('getDataIDs');
                    for (var i = 0; i < ids.length; i++) {
                        var id = ids[i];
                        var cancel = "<button class=\"btn btn-danger btn-sm\" type=\"button\" onclick=\"cancelRight('" + id + "')\">取消</button>";
                        jQuery("#table_list_my").jqGrid('setRowData', ids[i], { Cancel: cancel });
                    }
                }
            };
            var notMyConfig = {
                id: "table_list_notmy",
                pagerId: "pager_list_notmy",
                title: '尚未分配德角色',
                url: '@Url.Action("GetNotMyRoles")?UserId=@Model.Id',
                colNames: ['主键', '角色名称', '操作'],
                colModel: [
                    { name: 'id', index: 'id', width: 30, key: true, hidden: true },
                    { name: 'name', index: 'name', width: 120 },
                    { name: 'Authen', index: 'Authen', width: 30 }
                ],
                gridComplete: function() {
                    var ids = jQuery("#table_list_notmy").jqGrid('getDataIDs');
                    for (var i = 0; i < ids.length; i++) {
                        var id = ids[i];
                        var authen = "<button class=\"btn btn-info btn-sm\" type=\"button\" onclick=\"giveRight('" + id + "')\">授权</button>";
                        jQuery("#table_list_notmy").jqGrid('setRowData', ids[i], { Authen: authen });
                    }
                }
            };
            JucheapGrid.Load(myConfig);
            JucheapGrid.Load(notMyConfig);
        });
    </script>
}

JuCheap.Core.Web/Views/User/Edit.cshtml
@using JuCheap.Core.Infrastructure.Extentions
@model JuCheap.Core.Models.UserUpdateDto

@{
    ViewBag.Title = "编辑用户";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>编辑用户</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <form asp-controller="User" asp-action="Edit" class="form-horizontal" method="POST">
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="LoginName"></label>
                    <div class="col-sm-8">
                        <input asp-for="LoginName" class="form-control" placeholder="登录账号名" readonly="readonly"/>
                        <input asp-for="Id" type="hidden"/>
                        <span asp-validation-for="LoginName"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="RealName"></label>
                    <div class="col-sm-8">
                        <input asp-for="RealName" class="form-control" placeholder="真实姓名" />
                        <span asp-validation-for="RealName"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="Email"></label>
                    <div class="col-sm-8">
                        <input asp-for="Email" class="form-control" placeholder="邮箱" />
                        <span asp-validation-for="Email"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="Password"></label>
                    <div class="col-sm-8">
                        <input asp-for="Password" class="form-control" placeholder="登录密码" type="password" />
                        <span asp-validation-for="Password"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="ConfirmPwd"></label>
                    <div class="col-sm-8">
                        <input asp-for="ConfirmPwd" class="form-control" placeholder="请再次输入登录密码" type="password" />
                        <span asp-validation-for="ConfirmPwd"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="DepartmentId"></label>
                    <div class="col-sm-8">
                        <select id="DepartmentId" name="DepartmentId" class="form-control">
                            @if (!Model.DepartmentId.IsBlank())
                            {
                                <option value="@Model.DepartmentId" selected="selected">@Model.DepartmentName</option>
                            }
                        </select>
                        <span asp-validation-for="DepartmentId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                        <button class="btn btn-info" type="submit">保存</button>
                        <button class="btn btn-white" type="button" id="btnBack">返回</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section styles{
    <link href="~/js/plugins/select2/css/select2.css" rel="stylesheet" />
}
@section scripts{
    <environment names="Development">
        <script src="~/js/jquery.validate.js"></script>
        <script src="~/js/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/base.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/validate.min.js" asp-append-version="true"></script>
        <script src="~/js/base.min.js" asp-append-version="true"></script>
    </environment>
    <script src="~/js/plugins/select2/js/select2.js"></script>
    <script>
        $("#btnBack").bind("click", function (e) {
            XPage.GoTo(e.target, "@Url.Action("Index")");
        });
        $(function () {
            $('#DepartmentId').select2({
                placeholder: "所属部门",
                allowClear: true,
                ajax: {
                    url: '@Url.Action("GetDepartments", "Department")',
                    dataType: 'json'
                }
            });
        });
    </script>
}

JuCheap.Core.Web/Views/User/Index.cshtml
@{
    ViewBag.Title = "用户首页";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}
@section styles
{
    <environment names="Development">
        <link href="~/css/plugins/jqgrid/ui.jqgrid.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/grid.min.css" asp-append-version="true" />
    </environment>
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>用户管理</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="form-group">
                <button id="btnAdd" type="button" class="btn btn-primary " onclick="addModel()"><i class="fa fa-check"></i>&nbsp;添加</button>
                <button id="btnEdit" type="button" class="btn btn-info " onclick="editModel()"><i class="fa fa-paste"></i> 编辑</button>
                <button id="btnDel" type="button" class="btn btn-danger " onclick="delData()">
                    <i class="fa fa-dedent"></i>&nbsp;&nbsp;<span class="bold">删除</span>
                </button>
                <button id="btnSetRole" type="button" class="btn btn-info "><i class="fa fa-user"></i> 角色设置</button>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <input id="txtSearchKey" type="text" class="input form-control" placeholder="搜索关键字" />
                    <span class="input-group-btn">
                        <button id="btnSearch" class="btn btn btn-primary" type="button"> <i class="fa fa-search"></i> 搜索</button>
                    </span>
                </div>
            </div>

            <div class="jqGrid_wrapper">
                <table id="table_list"></table>
                <div id="pager_list"></div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <environment names="Development">
        <script src="~/js/plugins/jqgrid/jquery.jqGrid.js"></script>
        <script src="~/js/plugins/jqgrid/i18n/grid.locale-cn.js"></script>
        <script src="~/js/jqgrid-list.js"></script>
        <script src="~/js/json2.js"></script>
        <script src="~/js/base.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/grid.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        function addModel() {
            $("#btnAdd").button("loading");
            window.location.href = "@Url.Action("Add")";
        }

        function editModel() { //编辑
            var row = JucheapGrid.GetData();
            if (row != null) {
                $("#btnEdit").button("loading");
                window.location.href = "@Url.Action("Edit")/" + row.id;
            } else {
                alert("请选择要编辑的数据");
            }
        }

        function delData() { //删除
            XPage.DelData("@Url.Action("Delete")");
        }

        function searchData() { //搜索
            var json = {
                keywords: $("#txtSearchKey").val()
            };
            XPage.Search(json);
        }

        $(document).ready(function() {
            var config = {
                title: '用户列表',
                url: '@Url.Action("GetListWithPager")',
                colNames: ['主键', '登录名', '真实姓名','所属部门', '邮箱','超级管理员', '注册时间'],
                colModel: [
                    { name: 'id', index: 'id', width: 60, key: true, hidden: true },
                    { name: 'loginName', index: 'loginName', width: 60 },
                    { name: 'realName', index: 'realName', width: 60 },
                    { name: 'departmentName', index: 'departmentName', width: 120 },
                    { name: 'email', index: 'email', width: 60 },
                    {
                        name: 'isSuperMan',
                        index: 'isSuperMan',
                        width: 30,
                        align:'center',
                        formatter: function (cellValue, options, rowObject) {
                            return cellValue == true ? "<span class='btn btn-primary btn-rounded btn-xs'>是</span>" : "<span class='btn btn-danger btn-rounded btn-xs'>否</span>";
                        }
                    },
                    {
                        name: 'createDateTime',
                        index: 'createDateTime',
                        width: 60,
                        formatter: function(cellValue, options, rowObject) {
                            return cellValue;
                        }
                    }
                ]
            };
            JucheapGrid.Load(config);
            $("#btnSearch").bind("click", searchData);
            $("#btnSetRole").bind("click", function () {
                var row = JucheapGrid.GetData();
                if (row != null) {
                    //弹出即全屏
                    var layerIndex = parent.layer.open({
                        title: "用户角色授权",
                        type: 2,
                        content: '@Url.Action("Authen")/' + row.id + "?username=" + row.loginName,
                        area: ['800px', '600px'],
                        maxmin: true
                    });
                    parent.layer.full(layerIndex);
                } else {
                    parent.layer.alert("请选择要授权的用户");
                }
            });
        });
    </script>
}