JuCheap.Core.Web/Controllers/MessageController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using JuCheap.Core.Interfaces;
using JuCheap.Core.Models;
using JuCheap.Core.Models.Filters;
using JuCheap.Core.Web.Filters;
using JuCheap.Core.Web.Models;
using JuCheap.Core.Infrastructure.Extentions;
using Microsoft.AspNetCore.Authorization;
using JuCheap.Core.Infrastructure.Attributes;
using JuCheap.Core.Infrastructure.Menu;

namespace JuCheap.Core.Web.Controllers
{
    /// <summary>
    /// 站内信
    /// </summary>
    [Authorize]
    public class MessageController : Controller
    {
        private readonly IMessageService _messageService;

        public MessageController(IMessageService messageService)
        {
            _messageService = messageService;
        }

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.MessagePageId, ParentId = Menu.SystemId, Name = "站内信管理", Order = "8")]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 发送站内信
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.MessageAddId, ParentId = Menu.MessagePageId, Name = "发送站内信", Order = "1")]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// 发送站内信
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(MessageDto message)
        {
            await _messageService.SendAsync(message);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// 站内信详情
        /// </summary>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> Detail(string id)
        {
            var message = await _messageService.GetDetailsAsync(id);
            return View(message);
        }

        /// <summary>
        /// 阅读站内信
        /// </summary>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> Read(string id)
        {
            var message = await _messageService.GetDetailsAsync(id);
            await _messageService.ReadAsync(id, User.Identity.GetLoginUserId());
            return View(message);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [Menu(Id = Menu.MessageDeleteId, ParentId = Menu.MessagePageId, Name = "删除站内信", Order = "3")]
        public async Task<IActionResult> Delete([FromBody]IList<string> ids)
        {
            var result = new JsonResultModel<bool>();
            if (ids.AnyOne())
            {
                result.flag = await _messageService.DeleteAsync(ids);
            }
            return Json(result);
        }

        /// <summary>
        /// 搜索页面
        /// </summary>
        /// <param name="filters">查询参数</param>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> GetListWithPager(BaseFilter filters)
        {
            var result = await _messageService.SearchAsync(filters);
            return Json(result);
        }
    }
}

JuCheap.Core.Web/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using JuCheap.Core.Interfaces;
using JuCheap.Core.Models;
using JuCheap.Core.Models.Filters;
using JuCheap.Core.Web.Filters;
using JuCheap.Core.Web.Models;
using Microsoft.AspNetCore.Mvc;
using JuCheap.Core.Infrastructure.Extentions;
using Microsoft.AspNetCore.Authorization;
using System;
using JuCheap.Core.Infrastructure.Attributes;
using JuCheap.Core.Infrastructure.Menu;

namespace JuCheap.Core.Web.Controllers
{
    /// <summary>
    /// 用户
    /// </summary>
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;
        private readonly IMapper _mapper;

        public UserController(IUserService userSvc, IRoleService roleSvc, IMapper mapper)
        {
            _userService = userSvc;
            _roleService = roleSvc;
            _mapper = mapper;
        }

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.UserPageId, ParentId = Menu.SystemId, Name = "用户管理", Order = "7")]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 用户角色授权
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.UserRoleSetPageId, ParentId = Menu.UserPageId, Name = "用户角色授权", Order = "4")]
        public IActionResult Authen(string id)
        {
            var user = new UserDto
            {
                Id = id
            };
            return View(user);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.UserAddId, ParentId = Menu.UserPageId, Name = "添加用户", Order = "1")]
        public IActionResult Add()
        {
            return View(new UserAddDto());
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Menu(Id = Menu.UserEditId, ParentId = Menu.UserPageId, Name = "编辑用户", Order = "2")]
        public async Task<IActionResult> Edit(string id)
        {
            var dto = await _userService.FindAsync(id);
            var model = _mapper.Map<UserDto, UserUpdateDto>(dto);
            return View(model);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(UserAddDto dto)
        {
            if (ModelState.IsValid)
            {
                var result = await _userService.AddAsync(dto);
                if (result.IsNotBlank())
                    return RedirectToAction("Index");
            }
            return View(dto);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserUpdateDto dto)
        {
            if (ModelState.IsValid)
            {
                var result = await _userService.UpdateAsync(dto);
                if (result)
                    return RedirectToAction("Index");
            }
            return View(dto);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [Menu(Id = Menu.UserDeleteId, ParentId = Menu.UserPageId, Name = "删除用户", Order = "3")]
        public async Task<IActionResult> Delete([FromBody]List<string> ids)
        {
            var result = new JsonResultModel<bool>();
            if (ids.AnyOne())
            {
                result.flag = await _userService.DeleteAsync(ids);
            }
            return Json(result);
        }

        /// <summary>
        /// 搜索页面
        /// </summary>
        /// <param name="filters">查询参数</param>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> GetListWithPager(UserFilters filters)
        {
            var result = await _userService.SearchAsync(filters);
            return Json(result);
        }

        /// <summary>
        /// 我的角色
        /// </summary>
        /// <param name="filters">查询参数</param>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> GetMyRoles(RoleFilters filters)
        {
            var result = await _roleService.SearchAsync(filters);
            return Json(result);
        }

        /// <summary>
        /// 我尚未拥有的角色
        /// </summary>
        /// <param name="filters">查询参数</param>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<IActionResult> GetNotMyRoles(RoleFilters filters)
        {
            filters.ExcludeMyRoles = true;
            var result = await _roleService.SearchAsync(filters);
            return Json(result);
        }

        /// <summary>
        /// 用户角色授权
        /// </summary>
        /// <param name="id">角色ID</param>
        /// <param name="userId">用户Id</param>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.UserRoleSetId, ParentId = Menu.UserRoleSetPageId, Name = "用户角色授权", Order = "1")]
        public async Task<IActionResult> GiveRight(string id, string userId)
        {
            var result = new JsonResultModel<bool>
            {
                flag = await _userService.GiveAsync(userId, id)
            };
            return Json(result);
        }

        /// <summary>
        /// 用户角色取消
        /// </summary>
        /// <param name="id">角色ID</param>
        /// <param name="userId">用户Id</param>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.UserRoleCancelId, ParentId = Menu.UserRoleSetPageId, Name = "用户角色取消", Order = "2")]
        public async Task<IActionResult> CancelRight(string id, string userId)
        {
            var result = new JsonResultModel<bool>
            {
                flag = await _userService.CancelAsync(userId, id)
            };
            return Json(result);
        }

        /// <summary>
        /// 验证登录名是否重复
        /// </summary>
        /// <param name="loginName">登录名</param>
        /// <returns></returns>
        [HttpGet]
        [IgnoreRightFilter]
        public async Task<IActionResult> VerifyLoginName(string loginName)
        {
            var isExists = await _userService.ExistsLoginNameAsync(null, loginName);
            return isExists ? Json("登录帐号已存在") : Json(data: true);
        }

        /// <summary>
        /// 获取树
        /// </summary>
        /// <param name="q">查询关键字</param>
        /// <returns></returns>
        [HttpGet, IgnoreRightFilter]
        public async Task<ActionResult> GetUsers(string q)
        {
            var filter = new UserFilters
            {
                page = 1,
                rows = 1000,
                keywords = q
            };
            var result = await _userService.SearchAsync(filter);
            var users = new
            {
                results = result.rows.Select(x => new { id = x.Id, text = x.LoginName })
            };
            return Json(users);
        }
    }
}

JuCheap.Core.Web/Views/Message/Add.cshtml
@model JuCheap.Core.Models.MessageDto

@{
    ViewBag.Title = "添加站内信";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>@ViewBag.Title</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <form asp-controller="Message" asp-action="Add" class="form-horizontal" method="POST">
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="Title"></label>
                    <div class="col-sm-8">
                        <input asp-for="Title" class="form-control" placeholder="站内信标题"/>
                        <span asp-validation-for="Title"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="Contents"></label>
                    <div class="col-sm-8">
                        <textarea asp-for="Contents" class="form-control" placeholder="站内信内容"></textarea>
                        <span asp-validation-for="Contents"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">发送给所有人</label>
                    <div class="col-sm-8">
                        <select id="IsToAll" name="IsToAll" class="form-control">
                            <option value="false">否</option>
                            <option value="true">是</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" asp-for="UserIds"></label>
                    <div class="col-sm-8">
                        <select id="UserIds" name="UserIds" class="form-control" multiple="multiple"></select>
                        <span asp-validation-for="UserIds"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                        <button class="btn btn-info" type="submit">发送</button>
                        <button class="btn btn-white" type="button" id="btnBack">返回</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section styles{    
    <link href="~/js/plugins/select2/css/select2.css" rel="stylesheet" />
}

@section scripts{
    <environment names="Development">
        <script src="~/js/jquery.validate.js"></script>
        <script src="~/js/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/base.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/validate.min.js" asp-append-version="true"></script>
        <script src="~/js/base.min.js" asp-append-version="true"></script>
    </environment>    
    <script src="~/js/plugins/select2/js/select2.js"></script>
    <script>
        $("#btnBack").bind("click", function (e) {
            XPage.GoTo(e.target, "@Url.Action("Index")");
        });
        $("#IsToAll").change(function () { 
            var all = $(this).val();
            if (all === "true") {
                $("#UserIds").prop("disabled", true);
            } else {
                $("#UserIds").prop("disabled", false);
            }
        });
        $(function() {
            $('#UserIds').select2({
                placeholder: "请选择用户",
                tags:true,
                ajax: {
                    url: '@Url.Action("GetUsers", "User")',
                    dataType: 'json'
                }
            });
        });
    </script>
}

JuCheap.Core.Web/Views/Message/Detail.cshtml
@model JuCheap.Core.Models.MessageQueryDto

@{
    ViewBag.Title = "站内信详情";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}

<div class="wrapper wrapper-content">

    <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>站内信内容 </h5>
            </div>
            <div class="ibox-content">
                <p>标题：@Model.Title</p>
                <p>内容：@Model.Contents</p>
                <p>已读/总量：@Model.ReadedNumber / @Model.Total</p>
            </div>
        </div>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>用户名</th>
                    <th>是否已读</th>
                    <th>阅读日期</th>
                    <th>创建日期</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var detail in Model.Details)
                {
                    <tr>
                        <td>@detail.UserName</td>
                        <td>
                           @if (detail.IsReaded)
                           {
                               <i class="fa fa-check text-navy"></i>
                           }
                        </td>
                        <td>@detail.ReadDate?.ToShortDateString()</td>
                        <td>@detail.CreateDateTime</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

JuCheap.Core.Web/Views/Message/Index.cshtml
@{
    ViewBag.Title = "站内信管理";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}
@section styles
{
    <environment names="Development">
        <link href="~/css/plugins/jqgrid/ui.jqgrid.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/grid.min.css" asp-append-version="true" />
    </environment>
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>@ViewBag.Title</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="form-group">
                <button id="btnAdd" type="button" class="btn btn-primary " onclick="addModel()"><i class="fa fa-check"></i>&nbsp;发送站内信</button>
                <button id="btnDel" type="button" class="btn btn-danger " onclick="delData()">
                    <i class="fa fa-dedent"></i>&nbsp;&nbsp;<span class="bold">删除</span>
                </button>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <input id="txtSearchKey" type="text" class="input form-control" placeholder="搜索关键字" />
                    <span class="input-group-btn">
                        <button id="btnSearch" class="btn btn btn-primary" type="button"> <i class="fa fa-search"></i> 搜索</button>
                    </span>
                </div>
            </div>

            <div class="jqGrid_wrapper">
                <table id="table_list"></table>
                <div id="pager_list"></div>
            </div>
        </div>
    </div>
</div>

@section scripts
{

    <environment names="Development">
        <script src="~/js/plugins/jqgrid/jquery.jqGrid.js"></script>
        <script src="~/js/plugins/jqgrid/i18n/grid.locale-cn.js"></script>
        <script src="~/js/jqgrid-list.js"></script>
        <script src="~/js/json2.js"></script>
        <script src="~/js/base.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/grid.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        function addModel() {
            $("#btnAdd").button("loading");
            window.location.href = "@Url.Action("Add")";
        }

        function delData() {//删除
            XPage.DelData("@Url.Action("Delete")");
        }

        function searchData() {//搜索
            var json = {
                keywords: $("#txtSearchKey").val()
            };
            XPage.Search(json);
        }
        function showDetails(messageId) {
            parent.layer.open({
                title: '详情',
                type: 2,
                content: '/message/detail/' + messageId,
                area: ['80%', '60%']
            });
        }
        $(document).ready(function() {
            var config = {
                title: '站内信列表',
                url: '@Url.Action("GetListWithPager")',
                colNames: ['主键', '标题','已读数/总量', '创建时间', '操作'],
                colModel: [
                    { name: 'id', index: 'id', width: 60, key: true, hidden: true },
                    { name: 'title', index: 'title', width: 200 },
                    {
                        name: 'Total', index: 'Total', width: 30,
                        formatter: function (cellValue, options, rowObject) {
                            return rowObject.readedNumber + " / " + rowObject.total;
                        }
                    },
                    { name: 'createDateTime', index: 'createDateTime', width: 60 },
                    {
                        name: 'createDateTime', index: 'createDateTime', width: 30,align:'center',
                        formatter: function (cellValue, options, rowObject) {
                            return '<a class="btn btn-primary btn-xs" onclick="showDetails(\'' + rowObject.id + '\')">详情</a>';
                        }
                    }
                ]
            };
            JucheapGrid.Load(config);
            $("#btnSearch").bind("click", searchData);
        });
    </script>
}

JuCheap.Core.Web/Views/Message/Read.cshtml
@model JuCheap.Core.Models.MessageQueryDto

@{
    ViewBag.Title = "站内信详情";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}

<div class="wrapper wrapper-content">

    <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>站内信内容 </h5>
            </div>
            <div class="ibox-content">
                <p>标题：@Model.Title</p>
                <p>内容：@Model.Contents</p>
                <p>发送时间：@Model.CreateDateTime</p>
            </div>
        </div>
</div>