JuCheap.Core.Web/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using JuCheap.Core.Infrastructure.Attributes;
using JuCheap.Core.Infrastructure.Extentions;
using JuCheap.Core.Infrastructure.Menu;
using JuCheap.Core.Interfaces;
using JuCheap.Core.Models;
using JuCheap.Core.Models.Filters;
using JuCheap.Core.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace JuChea.Core.Web.Controllers
{
    public class AreaController : Controller
    {
        private readonly IAreaService _areaService;

        public AreaController(IAreaService areaService)
        {
            _areaService = areaService;
        }

        [Menu(Id = Menu.AreaPageId, ParentId = Menu.SystemId, Name = "省市区管理", Order = "2")]
        public ActionResult Index()
        {
            _areaService.UpdatePathCodes();
            return View();
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="id">父页面ID</param>
        /// <returns></returns>
        [Menu(Id = Menu.AreaPageAddId, ParentId = Menu.AreaPageId, Name = "添加省市区", Order = "1")]
        public async Task<ActionResult> Add(string id)
        {
            var parentDepartment = await _areaService.Find(id);
            var model = new AreaDto
            {
                ParentId = id
            };
            if (parentDepartment != null)
            {
                model.ParentName = parentDepartment.Name;
            }
            return View(model);
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Add(AreaDto model)
        {
            if (ModelState.IsValid)
            {
                var id = await _areaService.Add(model);
                if (id.IsNotBlank())
                {
                    return PartialView("CloseLayerPartial");
                }
            }
            return View(model);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Menu(Id = Menu.AreaPageEditId, ParentId = Menu.AreaPageId, Name = "编辑省市区", Order = "2")]
        public async Task<ActionResult> Edit(string id)
        {
            var model = await _areaService.Find(id);
            return View(model);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Edit(AreaDto model)
        {
            if (ModelState.IsValid)
            {
                var success = await _areaService.Update(model);
                if (success)
                {
                    return PartialView("CloseLayerPartial");
                }
            }
            return View(model);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id">主键ID</param>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.AreaPageDeleteId, ParentId = Menu.AreaPageId, Name = "删除省市区", Order = "3")]
        public async Task<ActionResult> Delete(string id)
        {
            var success = await _areaService.Delete(new List<string> { id });
            return Json(new { flag = success });
        }

        /// <summary>
        /// 获取树
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost, IgnoreRightFilter]
        public async Task<ActionResult> GetTrees(TreeFilter model)
        {
            var pages = await _areaService.FindByParentId(model.id);
            return Json(pages);
        }

        /// <summary>
        /// 判断是否存在
        /// </summary>
        /// <returns></returns>
        [IgnoreRightFilter]
        public async Task<ActionResult> Exists(string Id, string Name)
        {
            var exists = await _areaService.IsExists(Id, Name);
            return Json(!exists);
        }

    }
}

JuCheap.Core.Web/Controllers/SystemController.cs
using JuCheap.Core.Infrastructure.Attributes;
using JuCheap.Core.Infrastructure.Menu;
using JuCheap.Core.Interfaces;
using JuCheap.Core.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace JuCheap.Core.Web.Controllers
{
    /// <summary>
    /// 系统管理
    /// </summary>
    [Authorize]
    public class SystemController : Controller
    {
        private readonly IDatabaseInitService _databaseInitService;
        private readonly IMenuService _menuService;

        public SystemController(IDatabaseInitService databaseInitService, IMenuService menuService)
        {
            _databaseInitService = databaseInitService;
            _menuService = menuService;
        }

        /// <summary>
        /// 系统管理首页
        /// </summary>
        /// <returns></returns>
        [Menu(Id = Menu.SystemConfigId, ParentId = Menu.SystemId, Name = "系统配置", Order = "1")]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 重置路径码
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.ResetPathCodeId, ParentId = Menu.SystemConfigId, Name = "重置路径码", Order = "1")]
        public async Task<IActionResult> ReloadPathCode()
        {
            var result = new JsonResultModel<bool>
            {
                flag = await _databaseInitService.InitPathCodeAsync()
            };
            return Json(result);
        }

        /// <summary>
        /// 初始化省市区数据
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Menu(Id = Menu.ResetAreaId, ParentId = Menu.SystemConfigId, Name = "重置省市区基础数据", Order = "2")]
        public async Task<JsonResult> ReInitAreas()
        {
            var result = new JsonResultModel<bool>
            {
                flag = await _databaseInitService.InitAreas()
            };
            return Json(result);
        }

        /// <summary>
        /// 重置系统所有菜单
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> ReInitMenues()  
        {
            var menues = MenuHelper.GetMenues();
            var succes = await _menuService.ReInitMenuesAsync(menues);
            var result = new JsonResultModel<bool> { flag = succes };
            return Json(result);
        }
    }
}

JuCheap.Core.Web/Views/Area/Add.cshtml
@model JuCheap.Core.Models.AreaDto

@{
    ViewBag.Title = "添加";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}
<div class="wrapper wrapper-content">
    @using (Html.BeginForm("Add", "Area", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            <label class="col-sm-3 control-label">@Html.LabelFor(m => m.ParentName)：</label>
            <div class="col-sm-8">
                @Html.TextBoxFor(m => m.ParentName, new { @class = "form-control disabled", disabled = "disabled" })
                @Html.HiddenFor(m => m.ParentId)
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">@Html.LabelFor(m => m.Name)：</label>
            <div class="col-sm-8">
                @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">@Html.LabelFor(m => m.FullSpelling)：</label>
            <div class="col-sm-8">
                @Html.TextBoxFor(m => m.FullSpelling, new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.FullSpelling)
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">@Html.LabelFor(m => m.SimpleSpelling)：</label>
            <div class="col-sm-8">
                @Html.TextBoxFor(m => m.SimpleSpelling, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.SimpleSpelling)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-8">
                <button class="btn btn-info" type="submit" id="btnSave">添加</button>
                <button class="btn btn-white" type="button" id="btnBack" data-type="window">返回</button>
            </div>
        </div>
    }
</div>
@section scripts{
    <environment names="Development">
        <script src="~/js/jquery.validate.js"></script>
        <script src="~/js/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/base.js"></script>
        <script src="~/js/page/jucheap.action.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/validate.min.js" asp-append-version="true"></script>
        <script src="~/js/base.min.js" asp-append-version="true"></script>
        <script src="~/js/page/jucheap.action.js" asp-append-version="true"></script>
    </environment>
}

JuCheap.Core.Web/Views/Area/Edit.cshtml
@model JuCheap.Core.Models.AreaDto

@{
    ViewBag.Title = "编辑";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}
<div class="wrapper wrapper-content">
    @using (Html.BeginForm("Edit", "Area", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            <label class="col-sm-3 control-label">@Html.LabelFor(m => m.ParentName)：</label>
            <div class="col-sm-8">
                @Html.TextBoxFor(m => m.ParentName, new { @class = "form-control disabled", disabled = "disabled" })
                @Html.HiddenFor(m => m.ParentId)
                @Html.HiddenFor(m => m.Id)
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">@Html.LabelFor(m => m.Name)：</label>
            <div class="col-sm-8">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">@Html.LabelFor(m => m.FullSpelling)：</label>
            <div class="col-sm-8">
                @Html.TextBoxFor(m => m.FullSpelling, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FullSpelling)
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">@Html.LabelFor(m => m.SimpleSpelling)：</label>
            <div class="col-sm-8">
                @Html.TextBoxFor(m => m.SimpleSpelling, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.SimpleSpelling)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-8">
                <button class="btn btn-info" type="submit" id="btnSave">保存</button>
                <button class="btn btn-white" type="button" id="btnBack" data-type="window">返回</button>
            </div>
        </div>
    }
</div>
@section scripts{
    <environment names="Development">
        <script src="~/js/jquery.validate.js"></script>
        <script src="~/js/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/base.js"></script>
        <script src="~/js/page/jucheap.action.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/validate.min.js" asp-append-version="true"></script>
        <script src="~/js/base.min.js" asp-append-version="true"></script>
        <script src="~/js/page/jucheap.action.js" asp-append-version="true"></script>
    </environment>
}

JuCheap.Core.Web/Views/Area/Index.cshtml
@{
    ViewBag.Title = "省市区管理";
    Layout = "~/Views/Shared/_Layout_Content.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>省市区管理</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="form-group">
                <button id="btnAdd" type="button" class="btn btn-primary "><i class="fa fa-plus"></i>&nbsp;添加</button>
                <button id="btnEdit" type="button" class="btn btn-info "><i class="fa fa-pencil"></i> 编辑</button>
                <button id="btnDel" type="button" class="btn btn-danger ">
                    <i class="fa fa-remove"></i>&nbsp;&nbsp;<span class="bold">删除</span>
                </button>
                <button id="btnCancel" type="button" class="btn btn-warning "><i class="fa fa-undo"></i> 取消选中状态</button>
                <button type="button" class="btn btn-warning" id="btnReloadArea"><i class="fa fa-undo"></i> 重置省市区数据</button>
            </div>

            <div class="jqGrid_wrapper">
                <ul id="areaTree" class="ztree">
                    <li>数据加载中......</li>
                </ul>
                <input type="hidden" id="txtParentId"/>
            </div>
        </div>
    </div>
</div>
@section styles    {
    <link href="~/css/plugins/ztree/metroStyle.css" rel="stylesheet" />
}
@section scripts
{
<environment names="Development">
    <script src="~/js/base.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/js/base.min.js" asp-append-version="true"></script>
</environment>
    <script src="~/js/plugins/ztree/jquery.ztree.all.js"></script>
    <script src="~/js/page/jucheap.ztree.js"></script>
    <script type="text/javascript">
        var config = {
            id: 'areaTree',
            loadUrl: '@Url.Action("GetTrees")',
            addUrl: '@Url.Action("Add")',
            editUrl: '@Url.Action("Edit")',
            deleteUrl: '@Url.Action("Delete")',
            height: '360px',
            title:'区域信息'
        };
        var tree = new JuCheapTree(config);
        tree.load();
        $("#btnCancel").click(function() {
            var zTree = $.fn.zTree.getZTreeObj(config.id);
            zTree.cancelSelectedNode();
            $("#txtParentId").val("");
        });
        $(function() {
            $("#btnReloadArea").click(function() {
                XPage.DoPost(this, "@Url.Action("ReInitAreas", "System")", null, function() {
                    tree.load();
                }, null);
            });
        });
    </script>
}